NovostroyShop/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NovostroyShop.Filters;
using NovostroyShop.Models;
using NovostroyShop.Repositories;
using NovostroyShop.ViewModels;

namespace NovostroyShop.Controllers
{
    [CustomAuthorize]
    public class AdminController : Controller
    {
        private readonly IRepository<Category> _categoryRepository;
        private readonly IRepository<Brand> _brandRepository;
        private readonly IProductRepository _productRepository;

        public AdminController(IRepository<Category> categoryRepository, IRepository<Brand> brandRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _brandRepository = brandRepository;
            _productRepository = productRepository;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Categories = await _categoryRepository.GetAll();
            ViewBag.Brands = await _brandRepository.GetAll();
            ViewBag.Products = await _productRepository.GetAll();

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> SaveCategory(Category category)
        {
            if (category.Id == 0)
            {
                await _categoryRepository.Add(category);
            }
            else
            {
                var existingCategory = await _categoryRepository.GetById(category.Id);
                if (existingCategory != null)
                {
                    existingCategory.Name = category.Name;
                    await _categoryRepository.Update(existingCategory);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCategory(int id)
        {
            var category = await _categoryRepository.GetById(id);
            if (category != null)
            {
                await _categoryRepository.Delete(category);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SaveBrand(Brand brand)
        {
            if (brand.id == 0)
            {
                await _brandRepository.Add(brand);
            }
            else
            {
                var existingBrand = await _brandRepository.GetById(brand.id);
                if (existingBrand != null)
                {
                    existingBrand.Name = brand.Name;
                    await _brandRepository.Update(existingBrand);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBrand(int id)
        {
            var brand = await _brandRepository.GetById(id);
            if (brand != null)
            {
                await _brandRepository.Delete(brand);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SaveProduct(ProductViewModel product)
        {
            Product product1 = new Product();
            if (product.Id == 0)
            {
                product1.Category = await _categoryRepository.GetById(product.CategoryId);
                product1.Brand = await _brandRepository.GetById(product.BrandId);
                product1.Name = product.Name;
                product1.Description = product.Description;
                product1.Price = product.Price;
                product1.Discount = product.Discount;
                product1.ImageSrc = product.ImageSrc ?? "";
                product1.ImageSrc2 = product.ImageSrc2 ?? "";
                product1.ImageSrc3 = product.ImageSrc3 ?? "";
                product1.ImageSrc4 = product.ImageSrc4 ?? "";
                product1.ImageSrc5 = product.ImageSrc5 ?? "";
                product1.ReviewDetails = new List<ReviewDetail>();
                _productRepository.Add(product1);
            }
            else
            {
                var existingProduct = await _productRepository.GetById(product.Id);
                if (existingProduct != null)
                {
                    existingProduct.ImageSrc = product.ImageSrc ?? "";
                    existingProduct.ImageSrc2 = product.ImageSrc2 ?? "";
                    existingProduct.ImageSrc3 = product.ImageSrc3 ?? "";
                    existingProduct.ImageSrc4 = product.ImageSrc4 ?? "";
                    existingProduct.ImageSrc5 = product.ImageSrc5 ?? "";
                    existingProduct.Name = product.Name;
                    existingProduct.Description = product.Description;
                    existingProduct.Price = product.Price;
                    existingProduct.Discount = product.Discount;
                    existingProduct.Category = await _categoryRepository.GetById(product.CategoryId);
                    existingProduct.Brand = await _brandRepository.GetById(product.BrandId);
                    
                    _productRepository.Update(existingProduct);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            var product = await _productRepository.GetById(id);
            if (product != null)
            {
                await _productRepository.Delete(product);
            }
            return RedirectToAction("Index");
        }



    }
}

NovostroyShop/Controllers/AuthenticateController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using NovostroyShop.Authentication;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace NovostroyShop.Controllers
{
    public class AuthenticateController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public AuthenticateController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var userExists = await _userManager.FindByNameAsync(model.Username);
                if (userExists != null)
                {
                    ModelState.AddModelError(string.Empty, "Такой пользователь уже существует!");
                    return View(model);
                }

                ApplicationUser user = new ApplicationUser
                {
                    Email = model.Email,
                    SecurityStamp = Guid.NewGuid().ToString(),
                    UserName = model.Username
                };

                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("Index", "Products");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, false, lockoutOnFailure: false);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Products");
                }
                ModelState.AddModelError(string.Empty, "Неправильное имя пользователя или пароль.");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Products");
        }
    }
}

NovostroyShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Localization;
@using TranslatorHelper;

@{
    var currentAction = ViewContext.RouteData.Values["action"]?.ToString();
    var currentController = ViewContext.RouteData.Values["controller"]?.ToString();
    var cult = Context.Features.Get<IRequestCultureFeature>().RequestCulture.UICulture.Name;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Translate.GetWordFromArray("novostroy", cult)</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NovostroyShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a style="margin-left: 22%;
    font-weight: 500;
    font-family: system-ui;
    margin-right: 15%;" class="navbar-brand" asp-area="" asp-controller="Products" asp-action="Index">@Translate.GetWordFromArray("novostroy", cult)</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">@Translate.GetWordFromArray("home", cult)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutUs" asp-action="Index">@Translate.GetWordFromArray("about", cult)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Products">@Translate.GetWordFromArray("products", cult)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">@Translate.GetWordFromArray("admin_panel", cult)</a>
                        </li>
                        <li style="display: flex;
    align-items: center;
    margin-left: 25%;
    align-items: center;
    justify-content: space-between;
    width: 36px;" class="nav-item">
                            <a href="javascript:void(0);" onclick="setLanguage('en-US')">
                                <span style="font-size: 12px;" class="flag-icon flag-icon-us"></span>
                            </a>
                            <a href="javascript:void(0);" onclick="setLanguage('ru-RU')">
                                <span style="font-size: 12px;" class="flag-icon flag-icon-ru"></span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <button id="theme-toggle">
                                <i  id="sun-icon" class="bi bi-sun"></i>
                                <i  id="moon-icon" class="bi bi-moon"></i>
                            </button>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link cart-icon text-dark" href="/Cart/Index">
                                    <i style="font-size: 18px" class="bi bi-cart"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a style="font-size: large;color: black;" class="nav-link">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-area="" asp-controller="Authenticate" asp-action="Logout" method="post">
                                    <button type="submit" class="btn btn-link nav-link">
                                        <i style="font-size: 18px;color: black; " class="bi bi-box-arrow-right"></i>
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Authenticate" asp-action="Register">@Translate.GetWordFromArray("register", cult)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Authenticate" asp-action="Login">@Translate.GetWordFromArray("login", cult)</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @if (currentController == "Products" && currentAction == "Index")
    {
        <div style="margin-bottom: 100px;" class="row">
            <div class="col-12">
                <img style="width: 100%" class="img-fluid" src="/строймаг1.jpg" />
            </div>
        </div>
    }
    else if (currentController == "AboutUs" && currentAction == "Index")
    {
        <div style="margin-bottom: 100px;" class="row">
            <div class="col-12">
                <img style="width: 100%" class="img-fluid" src="/строймаг2.jpg" />
            </div>
        </div>
    }
    <div style="margin-bottom: 33%;" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div style="flex-direction: column;
    font-size: 15px;" class="container">
            <a style="color: #6c757d !important;" class="nav-link" asp-area="" asp-controller="Products" asp-action="Index">@Translate.GetWordFromArray("home", cult)</a>
            <a style="color: #6c757d !important;" class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">@Translate.GetWordFromArray("admin_panel", cult)</a>
            <a style="color: #6c757d !important;" class="nav-link" asp-area="" asp-controller="Сart" asp-action="Index">@Translate.GetWordFromArray("cart", cult)</a>
            <div class="col-12 text-center">
                <a href="https://www.instagram.com" class="footer-icon" target="_blank">
                    <i class="bi bi-instagram"></i>
                </a>
                <a href="https://www.facebook.com" class="footer-icon" target="_blank">
                    <i class="bi bi-facebook"></i>
                </a>
                <a href="tel:+1234567890" class="footer-icon">
                    <i class="bi bi-telephone"></i>
                </a>
            </div>
            <p>&copy; 2024 - @Translate.GetWordFromArray("novostroy", cult)</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>